### PR TITLE
update select-mock-targets config file

### PR DESCRIPTION
**Pull request by moustakas**
Update to `select-mock-targets.yaml` file based on https://github.com/desihub/desitarget/pull/325.

May also require https://github.com/desihub/desimodules/issues/22 to be resolved before merging to ensure `$DUST_DIR` is properly set.

### CODE REVIEW

**Comment by weaverba137** [comment]
@sbailey, should this be resolved *before* we run the mini test for 18.6?  If so, this also requires resolving exactly where `$DUST_DIR` will be set.

**Comment by sbailey** [comment]
Yes, let's get this resolved before 18.6.

Currently we've been using `/project/projectdirs/desi/software/edison/dust/v0_1/` which seems like a deprecated location.  Please pick something that seems like a better long term location (maybe `/project/projectdirs/desi/external/dust/v0_1/` or maybe even somewhere under `/project/projectdirs/cosmo/data`?) and create a "dust" product whose module load will set `$DUST_DIR` to that location.

The we (i.e. you :) ) can include that in the list of modules loaded by desimodules/test-release (and eventually 18.6), which opens the door for this PR to then use it.  That seems like a long chain, but it is a good part of quarterly housecleaning.

**Comment by moustakas** [comment]
Just a heads up that the imaging survey team uses 
`DUST_DIR=/global/project/projectdirs/desi/software/${NERSC_HOST}/dust/v0_0`
so let's keep everyone looped.  Pinging @dstndstn and @mlandriau so they're aware.

**Comment by weaverba137** [comment]
I can easily set up module files for both `v0_0` and `v0_1`.

**Comment by moustakas** [comment]
Here are the old module files we've moved away from in legacypipe (I don't know why there were separate ones for cori and edison):
  https://github.com/legacysurvey/legacypipe/blob/f2036e275b69462dbfa48d5100b133afd32b7c37/bin/modulefiles/cori/dust
  https://github.com/legacysurvey/legacypipe/tree/f2036e275b69462dbfa48d5100b133afd32b7c37/bin/modulefiles/edison/dust

For the record these were removed from the pipeline (in favor of a simple environment variable) in https://github.com/legacysurvey/legacypipe/pull/190

**Comment by weaverba137** [comment]
Heh, those had the dust data on `$SCRATCH`!  So there had to be separate versions.

**Comment by weaverba137** [comment]
Huh, it turns out that `/global/project/projectdirs/desi/software/${NERSC_HOST}/dust/v0_0` and `/global/project/projectdirs/desi/software/${NERSC_HOST}/dust/v0_1` are identical.  One is just a link to the other.  I'm going to copy the *data* to the cosmo repository.  The module files are already set up on cori, and once `20180518-1.2.5-spec` is installed on edison, I'll put them there as well.

**Comment by weaverba137** [comment]
Merging now so I can get back to running the test.

**Pull request merged**
